universe = vanilla
environment = CLASSPATH=../../mallet-2.0.7/class:../../mallet-2.0.7/lib/mallet-deps.jar 

Initialdir = wsj_larger
Executable = /usr/bin/java

+Group   = "GRAD"
+Project = "INSTRUCTIONAL"
+ProjectDescription = "CS388 Homework 2"

Log = exp6.log

Notification = complete
Notify_user = jianyu@cs.utexas.edu

Arguments = cc.mallet.fst.HMMSimpleTagger        --train true --model-file model_file        --training-proportion 1.0        --test lab ../../wsj/wsj81.pos ../../wsj/wsj82.pos

Output = exp6.out
Error  = exp6.err
Queue 1


